In [1]:
import bisect  
  
def insert(list, n):
    bisect.insort(list, n) 
    return list
  

list = [1, 2, 4]
n = eval(input("enter the value to be inserted "))
  
print(insert(list, n))


enter the value to be inserted 6
[1, 2, 4, 6]


In [3]:
def linearSearch(array, n, x):
    for i in range(0, n):
        if (array[i] == x):
            return i
    return -1


array = [2, 4, 0, 1, 9]
x = eval(input("enter the element to be searched: "))
n = len(array)
result = linearSearch(array, n, x)
if(result == -1):
    print("Element not found")
else:
    print("Element found at index: ", result)

enter the element to be searched: 9
Element found at index:  4


In [4]:
class Base:
    def __init__(self):
        self.a = 10
        self._b = 20
        
    def display(self):
         print(" the values are :")
         print(f"a={self.a} b={self._b}")

class Derived(Base):                                   # Creating a derived class
    def __init__(self):         
        Base.__init__(self)                        # Calling constructor of Base class
        self.d = 30
        
    def display(self):
        Base.display(self)
        print(f"d={self.d}")

    def __add__(self, ob):
        return self.a + ob.a+self.d + ob.d
        #return self.a + ob.a+self.d + ob.d+self.b + ob.b


obj1 = Base()
obj2 = Derived()
obj3 = Derived()


obj2.display()
obj3.display()

print("\n Sum of two objects :",obj2 + obj3)

    
    

 the values are :
a=10 b=20
d=30
 the values are :
a=10 b=20
d=30

 Sum of two objects : 80


In [9]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print("concate with axis=0 :",np.concatenate((a, b), axis=0))
print("concate with axis=0 :",np.concatenate ((a, b.T), axis=1))

np.concatenate((a, b), axis=None)


concate with axis=0 : [[1 2]
 [3 4]
 [5 6]]
concate with axis=0 : [[1 2 5]
 [3 4 6]]


array([1, 2, 3, 4, 5, 6])

In [11]:
a = np.array([[12,4,5],[23,45,66],[45,34,23]])
b = np.array([[1,40,50],[2,4,6],[4,3,2]])

In [12]:
np.vstack((a,b))

array([[12,  4,  5],
       [23, 45, 66],
       [45, 34, 23],
       [ 1, 40, 50],
       [ 2,  4,  6],
       [ 4,  3,  2]])

In [13]:
np.hstack((a,b))

array([[12,  4,  5,  1, 40, 50],
       [23, 45, 66,  2,  4,  6],
       [45, 34, 23,  4,  3,  2]])

In [14]:
a.reshape(3,3)

array([[12,  4,  5],
       [23, 45, 66],
       [45, 34, 23]])

In [15]:
a=[1,3,2,6,7,8,9]
np.sort(a)

array([1, 2, 3, 6, 7, 8, 9])

In [16]:
np.argsort(a)

array([0, 2, 1, 3, 4, 5, 6], dtype=int64)

In [17]:
np.sort_complex(a)

array([1.+0.j, 2.+0.j, 3.+0.j, 6.+0.j, 7.+0.j, 8.+0.j, 9.+0.j])

In [19]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 5)
print(x)

arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)


(array([3, 5, 6], dtype=int64),)
0
[1 2 3]


In [20]:
import numpy as np

x = np.arange(9.0)
print(x)
print(np.split(x, 3))                # with no of partitions N, 
print(np.split(x, [3, 5, 6, 10]))   # with indices

#the array will be divided into N equal arrays along axis. If such a split is not possible, an error is raised.

x = np.arange(9)
np.array_split(x, 4)               

#Split an array into multiple sub-arrays of equal or near-equal size. Does not raise an exception if an equal division cannot be made.

a = np.array([[1, 3, 5, 7, 9, 11],
              [2, 4, 6, 8, 10, 12]])
  
# horizontal splitting
print("Splitting along horizontal axis into 2 parts:\n", np.hsplit(a, 2))
  
# vertical splitting
print("\nSplitting along vertical axis into 2 parts:\n", np.vsplit(a, 2))

[0. 1. 2. 3. 4. 5. 6. 7. 8.]
[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]
[array([0., 1., 2.]), array([3., 4.]), array([5.]), array([6., 7., 8.]), array([], dtype=float64)]
Splitting along horizontal axis into 2 parts:
 [array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]

Splitting along vertical axis into 2 parts:
 [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]
